version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: recursivedine-postgres-dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker-init/000_create_database.sql:/docker-entrypoint-initdb.d/000_create_database.sql
      - ./migrations/001_initial_schema.sql:/docker-entrypoint-initdb.d/001_initial_schema.sql
      - ./migrations/002_add_user_fields.sql:/docker-entrypoint-initdb.d/002_add_user_fields.sql
      - ./migrations/003_add_vat_and_cashier_fields.sql:/docker-entrypoint-initdb.d/003_add_vat_and_cashier_fields.sql
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: recursivedine-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - dev-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: recursivedine-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_dev_data:/prometheus
    networks:
      - dev-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: recursivedine-grafana-dev
    ports:
      - "3000:3000"
    volumes:
      - grafana_dev_data:/var/lib/grafana
    networks:
      - dev-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  postgres_dev_data:
    name: recursivedine_postgres_dev_data
  redis_dev_data:
    name: recursivedine_redis_dev_data
  prometheus_dev_data:
    name: recursivedine_prometheus_dev_data
  grafana_dev_data:
    name: recursivedine_grafana_dev_data

networks:
  dev-network:
    name: recursivedine-dev-network
    driver: bridge
